name: luma_av PR Checks
on:
  pull_request:
    branches:
      - luma/ci_updates
jobs:
  build_and_test_with_gcc:
    runs-on: ubuntu-latest
    container: 
      image: lumauwu/luma_gcc_ci:test
      options: --workdir /
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: conan install (Release)
        timeout-minutes: 2
        run: conan install . -if build --build missing -s build_type=Release
      - name: build
        run: conan build . -bf build
      - name: run unit tests
        run: ./build/bin/luma_av_unit 
        
  clang_tooling:
    runs-on: ubuntu-latest
    container: 
      image: lumauwu/luma_clang_ci:test
      options: --workdir /
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: conan install (Release)
        timeout-minutes: 2
        run: conan install . --profile clang-libcxx -if build --build missing -s build_type=Release
      - name: build
        run: conan build . -bf build
      - name: clang-tidy (diff)
        run: python3 /llvm-install/scripts/clang-tidy-diff.py -clang-tidy-binary /llvm-install/bin/clang-tidy
        working-directory: ./build
      - name: run unit tests
        run: ./build/bin/luma_av_unit
      - name: apply clang-format (diff)
        run: python3 /llvm-install/scripts/clang-format-diff.py -sort-includes -binary /llvm-install/bin/clang-format
      - name: commit format changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "['src/', 'tests/', 'examples/']"
