name: PR Reminders
on:
  pull_request:
    branches:
      - main
jobs:
  drink_water_reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: reminder to drink water 
        run: echo "hey please remember to drink some water and stretch and eat food and stuff (:"